FROM python:3.9-alpine

ENV PYTHONBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app

RUN apk add bash

RUN pip install --upgrade pip
RUN pip install pipenv

COPY . .
RUN pipenv install --system --dev
