#!/bin/bash

ppid=$$
case $1 in
    -l)
        dirstory blist $ppid $2
        ;;
    -h|--help)
        dirstory back --help
        ;;
    *)
        step_back_path=""
        step_back_path=$(dirstory back $ppid)
        command cd "${step_back_path}" || exit
        ;;
esac
